services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: graphqlapi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d graphqlapi"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: